"use client";
import Link from "next/link";
import { useState } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import type { UserDTO, AuditDTO } from "@/lib/dto";
import { date, label } from "@/lib/labels";
import { userCreate } from "@/lib/validation";
import { Badge, DataForm, Empty, ErrorBox, Loading, Title, mutate, options, useResource } from "./common";
import { Button } from "./ui/button";
import { Dialog } from "./ui/dialog";
export function AdminPage({ section }: { section: string }) {
  if (section === "users") return <UsersPage />;
  if (section === "audit") return <AuditPage />;
  if (section === "permissions") return <PermissionsPage />;
  return <ArchivedPage />;
}
function UsersPage() {
  const { data, error, loading, reload } = useResource<UserDTO[]>("users");
  const [modal, setModal] = useState(""); const [selected, setSelected] = useState<UserDTO>();
  const done = () => { setModal(""); reload(); };
  return <><Title title="Tài khoản đội ngũ" description="Quản lý quyền hệ thống và bảo vệ phiên đăng nhập."><Button onClick={() => setModal("create")}>+ Tạo tài khoản</Button></Title><section className="panel">{loading ? <Loading /> : error ? <ErrorBox message={error} retry={reload} /> : <div className="table-scroll"><table><thead><tr><th>Thành viên</th><th>Vai trò</th><th>Trạng thái</th><th>Mật khẩu</th><th>Thao tác</th></tr></thead><tbody>{data?.map(u => <tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}</small><small>Mã: {u.id}</small></td><td><Badge value={u.role} /></td><td><Badge value={u.status} /></td><td>{u.mustChangePassword ? "Cần đổi mật khẩu tạm" : "Đã thiết lập"}</td><td><div className="actions"><Button variant="outline" size="sm" onClick={() => { setSelected(u); setModal("edit"); }}>Sửa / khóa</Button><Button variant="ghost" size="sm" onClick={() => { setSelected(u); setModal("reset"); }}>Cấp lại mật khẩu</Button></div></td></tr>)}</tbody></table></div>}</section><Dialog open={!!modal} onOpenChange={v => { if (!v) setModal(""); }} title={modal === "create" ? "Tạo tài khoản" : modal === "reset" ? "Cấp lại mật khẩu tạm" : "Quản lý tài khoản"} description="Mật khẩu tạm chỉ đăng nhập được một lần. Chia sẻ trực tiếp với thành viên.">{modal === "create" && <DataForm fields={[{ name: "name", label: "Họ tên", required: true }, { name: "email", label: "Email", type: "email", required: true }, { name: "role", label: "Vai trò", options: options(["MEMBER", "ADMIN"]) }, { name: "temporaryPassword", label: "Mật khẩu tạm (ít nhất 12 ký tự)", type: "password", required: true }]} initial={{ role: "MEMBER" }} schema={userCreate} submit={v => mutate("users", v)} onDone={done} submitLabel="Tạo tài khoản" />}{modal === "edit" && selected && <DataForm fields={[{ name: "name", label: "Họ tên", required: true }, { name: "role", label: "Vai trò", options: options(["MEMBER", "ADMIN"]) }, { name: "status", label: "Trạng thái", options: options(["ACTIVE", "LOCKED"]) }]} initial={selected} submit={v => mutate(`users/${selected.id}`, { ...v, expectedVersion: selected.version }, "PATCH")} onDone={done} submitLabel="Xác nhận (đổi quyền / khóa sẽ thu hồi phiên)" />}{modal === "reset" && selected && <DataForm fields={[{ name: "temporaryPassword", label: "Mật khẩu tạm mới (ít nhất 12 ký tự)", type: "password", required: true }]} submit={v => mutate(`users/${selected.id}/reset`, { ...v, expectedVersion: selected.version })} onDone={done} submitLabel="Cấp lại và thu hồi mọi phiên đăng nhập" />}</Dialog></>;
}
function PermissionsPage() {
  const { data, error, loading, reload } = useResource<{ propertyId: string; userId: string; canEdit: boolean; canViewSensitive: boolean; user: { name: string; email: string }; property: { id: string; code: string; title: string }; grantedBy: { name: string } }[]>("permissions");
  return <><Title title="Phân quyền hồ sơ" description="Hai quyền độc lập. Mở hồ sơ để cấp, chỉnh sửa hoặc thu hồi." /><section className="panel">{loading ? <Loading /> : error ? <ErrorBox message={error} retry={reload} /> : !data?.length ? <Empty>Chưa có quyền riêng nào được cấp.</Empty> : <div className="table-scroll"><table><thead><tr><th>Hồ sơ</th><th>Thành viên</th><th>Sửa hồ sơ</th><th>Xem riêng tư</th><th>Người cấp</th></tr></thead><tbody>{data.map(p => <tr key={`${p.propertyId}-${p.userId}`}><td><Link className="text-link" href={`/properties/${p.propertyId}`}>{p.property.code}<small>{p.property.title}</small></Link></td><td>{p.user.name}<small>{p.user.email}</small></td><td>{p.canEdit ? "Có" : "Không"}</td><td>{p.canViewSensitive ? "Có" : "Không"}</td><td>{p.grantedBy.name}</td></tr>)}</tbody></table></div>}</section></>;
}
function ArchivedPage() {
  const { data, error, loading, reload } = useResource<{ id: string; code: string; title: string; archivedAt: string; version: number }[]>("archived"); const [restore, setRestore] = useState<{ id: string; version: number }>(); const [actionError, setActionError] = useState("");
  return <><Title title="Hồ sơ đã lưu trữ" description="Khôi phục về Tạm ngưng để kiểm tra trước khi hiển thị lại." /><section className="panel">{loading ? <Loading /> : error ? <ErrorBox message={error} retry={reload} /> : !data?.length ? <Empty>Không có hồ sơ lưu trữ.</Empty> : <div className="table-scroll"><table><thead><tr><th>Hồ sơ</th><th>Ngày lưu trữ</th><th /></tr></thead><tbody>{data.map(p => <tr key={p.id}><td><Link className="text-link" href={`/properties/${p.id}`}>{p.code} · {p.title}</Link></td><td>{date(p.archivedAt)}</td><td><Button variant="outline" onClick={() => setRestore(p)}>Khôi phục</Button></td></tr>)}</tbody></table></div>}</section><Dialog open={!!restore} onOpenChange={() => setRestore(undefined)} title="Khôi phục hồ sơ?"><p>Các đợt giao dịch và lịch sử được giữ nguyên. Hồ sơ sẽ ở trạng thái Tạm ngưng.</p>{actionError && <ErrorBox message={actionError} />}<Button onClick={async () => { try { await mutate(`properties/${restore!.id}/visibility`, { visibility: "PAUSED", expectedVersion: restore!.version }); setRestore(undefined); reload(); } catch (e) { setActionError((e as Error).message); } }}>Xác nhận khôi phục</Button></Dialog></>;
}
function AuditPage() {
  const params = useSearchParams(); const router = useRouter(); const { data, error, loading, reload } = useResource<{ items: AuditDTO[]; total: number; page: number; pages: number }>(`audit?${params}`);
  const set = (key: string, value: string) => { const q = new URLSearchParams(params); if (value) q.set(key, value); else q.delete(key); if (key !== "page") q.delete("page"); router.replace(`?${q}`); };
  return <><Title title="Nhật ký hệ thống" description="Lịch sử chỉ đọc. Giá trị cũ / mới và người thực hiện được lưu cùng giao dịch." /><section className="panel"><div className="advanced-filters">{[{ key: "actorId", name: "Mã người thực hiện" }, { key: "entity", name: "Đối tượng (Property, Listing, User…)" }, { key: "action", name: "Thao tác (UPDATE, STATUS…)" }, { key: "from", name: "Từ ngày", type: "date" }, { key: "to", name: "Đến ngày", type: "date" }].map(f => <label className="filter-field" key={f.key}>{f.name}<input type={f.type ?? "text"} value={params.get(f.key) ?? ""} onChange={e => set(f.key, e.target.value)} /></label>)}<Button variant="ghost" onClick={() => router.replace("/audit")}>Đặt lại</Button></div>{loading ? <Loading /> : error ? <ErrorBox message={error} retry={reload} /> : !data?.items.length ? <Empty /> : <>{data.items.map(a => <details className="history-item" key={a.id}><summary><strong>{label(a.action)}</strong> · {a.actor.name} · {a.entity}{a.sensitive && " · Riêng tư"}<small>{date(a.createdAt)}</small></summary><pre>{JSON.stringify(a.diff, null, 2)}</pre></details>)}<div className="pagination"><span>{data.total} thay đổi · Trang {data.page}/{data.pages}</span><div className="actions"><Button variant="outline" disabled={data.page <= 1} onClick={() => set("page", String(data.page - 1))}>Trước</Button><Button variant="outline" disabled={data.page >= data.pages} onClick={() => set("page", String(data.page + 1))}>Sau</Button></div></div></>}</section></>;
}
