"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowUpRight, Building2, Search, SlidersHorizontal, Clock3, KeyRound, House, ArrowRight, Users } from "lucide-react";
import { Badge, Empty, ErrorBox, Loading, Title, useResource } from "./common";
import { Button } from "./ui/button";
import { date, label, money } from "@/lib/labels";
import { propertyTypes, statuses } from "@/lib/validation";
import type { ListDTO } from "@/lib/dto";
type DashboardDTO = { counts: { transactionType: string; status: string; _count: number }[]; stale: { transactionType: string; _count: number }[]; assigned: number; recent: { id: string; action: string; createdAt: string; actor: { name: string }; property: { id: string; code: string; title: string } }[]; drafts: { id: string; code: string; title: string }[] };
export function Dashboard() {
  const { data, loading, error, reload } = useResource<DashboardDTO>("dashboard");
  if (loading) return <Loading />; if (error || !data) return <ErrorBox message={error} retry={reload} />;
  const active = (type: string) => data.counts.filter(x => x.transactionType === type && ["AVAILABLE", "DEPOSITED"].includes(x.status)).reduce((s, x) => s + x._count, 0);
  return <><Title title="Tổng quan" description="Nguồn hàng, tình trạng và hoạt động của đội ngũ trong một góc nhìn." /><section className="welcome-banner"><div><span className="welcome-chip">KHO BẤT ĐỘNG SẢN NỘI BỘ</span><h2>Mỗi hồ sơ rõ ràng,<br />thêm một cơ hội kết nối.</h2><p>Kiểm tra nguồn hàng, cập nhật tình trạng và tìm bất động sản phù hợp.</p><Link href="/rent">Khám phá kho cho thuê <ArrowRight size={17} /></Link></div><div className="building-art" aria-hidden="true"><div className="building back" /><div className="building front">{Array.from({ length: 12 }, (_, i) => <span key={i} />)}</div><div className="art-ground" /></div></section>
    <div className="stats-grid">{[{ title: "Đang chào cho thuê", value: active("RENT"), href: "/rent", icon: KeyRound, color: "green" }, { title: "Đang chào mua bán", value: active("SALE"), href: "/sale", icon: House, color: "blue" }, { title: "Cần kiểm tra lại", value: data.stale.reduce((s, x) => s + x._count, 0), href: "/rent?stale=true", icon: Clock3, color: "amber" }, { title: "Hồ sơ được quyền sửa", value: data.assigned, href: "/rent?mine=true", icon: Users, color: "purple" }].map(card => <Link className="stat-card" href={card.href} key={card.title}><div><span className={`stat-icon ${card.color}`}><card.icon size={20} /></span><ArrowUpRight size={17} className="muted" /></div><strong>{card.value}</strong><p>{card.title}</p></Link>)}</div>
    <div className="dashboard-columns"><section className="panel"><div className="section-heading"><div><h2>Tình trạng nguồn hàng</h2><p className="muted">Các đợt giao dịch mới nhất</p></div><Building2 size={20} /></div><div className="status-summary">{["RENT", "SALE"].map(type => <div key={type}><h3>{label(type)}</h3>{statuses.filter(s => !(type === "RENT" && s === "SOLD") && !(type === "SALE" && s === "RENTED")).map(status => <Link key={status} href={`/${type === "RENT" ? "rent" : "sale"}?status=${status}`}><Badge value={status} /><strong>{data.counts.find(x => x.transactionType === type && x.status === status)?._count ?? 0}</strong><ArrowUpRight size={14} /></Link>)}<Link href={`/${type === "RENT" ? "rent" : "sale"}?stale=true`}><span className="muted">Cần kiểm tra lại</span><strong>{data.stale.find(x => x.transactionType === type)?._count ?? 0}</strong></Link></div>)}</div></section><section className="panel"><div className="section-heading"><div><h2>Hoạt động gần đây</h2><p className="muted">Những hồ sơ bạn được quyền theo dõi</p></div></div>{data.recent.length ? <div className="activity-list">{data.recent.map(item => <Link href={`/properties/${item.property.id}`} key={item.id}><span className="activity-dot" /><div><strong>{label(item.action)}</strong><p>{item.property.code} · {item.property.title || "Chưa đặt tiêu đề"}</p><small>{item.actor.name} · {date(item.createdAt)}</small></div></Link>)}</div> : <Empty>Chưa có hoạt động trong phạm vi quyền của bạn.</Empty>}</section></div>
    {data.drafts.length > 0 && <section className="panel"><div className="section-heading"><h2>Tiếp tục hoàn thiện bản nháp</h2><Badge value="DRAFT" /></div><div className="draft-list">{data.drafts.map(p => <Link key={p.id} href={`/properties/${p.id}`}><span>{p.code}</span><strong>{p.title || "Hồ sơ chưa có tiêu đề"}</strong><ArrowRight size={18} /></Link>)}</div></section>}
  </>;
}
export function Inventory({ type }: { type: "RENT" | "SALE" }) {
  const params = useSearchParams(); const router = useRouter();
  const [search, setSearch] = useState(params.get("q") ?? ""); const [advanced, setAdvanced] = useState(false);
  const query = params.toString();
  const set = (key: string, value: string) => { const next = new URLSearchParams(query); if (value) next.set(key, value); else next.delete(key); if (key !== "page") next.delete("page"); router.replace(`?${next}`, { scroll: false }); };
  useEffect(() => { if (search === (params.get("q") ?? "")) return; const timer = setTimeout(() => { const next = new URLSearchParams(query); if (search) next.set("q", search); else next.delete("q"); next.delete("page"); router.replace(`?${next}`, { scroll: false }); }, 350); return () => clearTimeout(timer); }, [search, params, query, router]);
  const { data, error, loading, reload } = useResource<ListDTO>(`properties?${query}&transactionType=${type}`);
  const select = (key: string, name: string, values: readonly string[]) => <label className="filter-field">{name}<select value={params.get(key) ?? ""} onChange={e => set(key, e.target.value)}><option value="">Tất cả</option>{values.map(v => <option value={v} key={v}>{label(v)}</option>)}</select></label>;
  return <><Title title={type === "RENT" ? "Kho cho thuê" : "Kho mua bán"} description="Tìm đúng nguồn hàng. Theo dõi từng đợt giao dịch." /><section className="panel inventory-panel"><div className="inventory-toolbar"><div className="search-input"><Search size={19} /><input aria-label="Tìm bất động sản" placeholder="Tìm mã, tiêu đề, địa chỉ, dự án…" value={search} onChange={e => setSearch(e.target.value)} /></div><Button variant="outline" onClick={() => setAdvanced(v => !v)}><SlidersHorizontal size={17} />Bộ lọc</Button><label className="sr-only" htmlFor="sort">Sắp xếp</label><select id="sort" value={params.get("sort") ?? "updated"} onChange={e => set("sort", e.target.value)}><option value="updated">Mới cập nhật</option><option value="priceAsc">Giá tăng dần</option><option value="priceDesc">Giá giảm dần</option><option value="oldestConfirmed">Lâu chưa xác nhận</option></select></div><div className="quick-filters">{select("propertyType", "Loại hình", propertyTypes)}{select("status", "Trạng thái", statuses.filter(s => type === "RENT" ? s !== "SOLD" : s !== "RENTED"))}<label className="check"><input type="checkbox" checked={params.get("mine") === "true"} onChange={e => set("mine", e.target.checked ? "true" : "")} />Tôi được quyền sửa</label><label className="check"><input type="checkbox" checked={params.get("stale") === "true"} onChange={e => set("stale", e.target.checked ? "true" : "")} />Cần kiểm tra lại</label></div>
      {advanced && <div className="advanced-filters">{[{ key: "region", title: "Tỉnh / thành phố" }, { key: "minPrice", title: "Giá từ (VND)" }, { key: "maxPrice", title: "Giá đến (VND)" }, { key: "minArea", title: "Diện tích sử dụng từ (m²)" }, { key: "maxArea", title: "Diện tích đến (m²)" }, { key: "bedrooms", title: "Số phòng ngủ tối thiểu" }, { key: "responsibleUserId", title: "Mã người phụ trách" }].map(f => <label className="filter-field" key={f.key}>{f.title}<input type={["region", "responsibleUserId"].includes(f.key) ? "text" : "number"} min="0" value={params.get(f.key) ?? ""} onChange={e => set(f.key, e.target.value)} /></label>)}{type === "RENT" && <label className="filter-field">Kỳ giá khi lọc / sắp xếp<select value={params.get("rentPeriod") ?? "MONTH"} onChange={e => set("rentPeriod", e.target.value)}><option value="MONTH">Theo tháng</option><option value="YEAR">Theo năm</option></select></label>}{select("visibility", "Hiển thị", ["DRAFT", "PUBLISHED", "PAUSED"])}<Button variant="ghost" onClick={() => { setSearch(""); router.replace(type === "RENT" ? "/rent" : "/sale"); }}>Đặt lại bộ lọc</Button></div>}
      <div className="results-meta"><span><strong>{data?.total ?? "…"}</strong> đợt giao dịch</span><span>Giá gốc được hiển thị cùng kỳ giá · Diện tích sử dụng</span></div>
      {loading ? <Loading /> : error ? <ErrorBox message={error} retry={reload} /> : !data?.items.length ? <Empty>Thử thay đổi từ khóa hoặc đặt lại bộ lọc.</Empty> : <><div className="inventory-table"><div className="inventory-row inventory-head"><span>Bất động sản</span><span>Diện tích</span><span>Giá chào</span><span>Trạng thái</span><span>Xác nhận gần nhất</span><span /></div>{data.items.map(item => <Link className="inventory-row" href={`/properties/${item.propertyId}`} key={item.id}><div className="property-cell"><div className="thumbnail">{item.property.images[0] ? <img src={`/api/app/images/${item.property.images[0].id}`} alt={item.property.title} /> : <Building2 size={28} />}</div><div><small>{item.property.code} · {label(item.property.propertyType)}</small><h3>{item.property.title || "Chưa đặt tiêu đề"}</h3><p>{item.property.wardCommune}, {item.property.provinceCity}</p><small>{item.property.responsibleUser?.name ?? "Chưa có người phụ trách"}</small></div></div><div className="area-cell"><strong>{item.property.usableArea ?? "—"} m²</strong><small>{item.property.bedrooms ?? "—"} phòng ngủ</small></div><div className="price-cell"><strong>{money(item.amount)}</strong><small>{item.transactionType === "RENT" ? `/${label(item.rentPeriod ?? "MONTH")}` : "Giá bán"} · {label(item.priceMode)}</small></div><div><Badge value={item.status} />{item.property.visibility !== "PUBLISHED" && <small>{label(item.property.visibility)}</small>}</div><div className={item.stale ? "stale-cell" : "confirmed-cell"}><span>{date(item.lastConfirmedAt)}</span>{item.stale && <small><Clock3 size={12} />Cần kiểm tra lại</small>}</div><ArrowUpRight size={18} className="row-arrow" /></Link>)}</div><div className="pagination"><span>Trang {data.page} / {data.pages} · {data.total} kết quả</span><div className="actions"><Button variant="outline" disabled={data.page <= 1} onClick={() => set("page", String(data.page - 1))}>Trước</Button><Button variant="outline" disabled={data.page >= data.pages} onClick={() => set("page", String(data.page + 1))}>Sau</Button></div></div></>}
    </section></>;
}
