"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Pencil, Plus, ShieldCheck, Check, Clock3, ArrowUp, ArrowDown, Trash2, Star, Upload } from "lucide-react";
import type { PropertyDTO, ListingDTO, UserDTO } from "@/lib/dto";
import { date, label, money } from "@/lib/labels";
import { commissionSchema, ownerSchema } from "@/lib/validation";
import { ApiError, Badge, DataForm, Empty, ErrorBox, Loading, Title, mutate, options, useResource } from "./common";
import { Button } from "./ui/button";
import { Dialog } from "./ui/dialog";
import { PropertyForm, ListingForm, listingFormFields, normalizeFields } from "./property-forms";
export function NewProperty() { return <><Title title="Thêm bất động sản" description="Bắt đầu với bản nháp. Thêm ảnh và một đợt giao dịch trước khi hiển thị." /><section className="panel"><PropertyForm /></section></>; }
export function PropertyDetail({ id }: { id: string }) {
  const { data: p, loading, error, reload } = useResource<PropertyDTO>(`properties/${id}`);
  const [modal, setModal] = useState(""); const [tab, setTab] = useState("RENT"); const [message, setMessage] = useState(""); const [actionError, setActionError] = useState(""); const [lightbox, setLightbox] = useState<string>();
  if (loading) return <Loading />; if (error || !p) return <ErrorBox message={error} retry={reload} />;
  const done = () => { setModal(""); reload(); setMessage("Đã lưu thay đổi."); };
  const act = async (path: string, data: unknown) => { setActionError(""); try { await mutate(path, data); reload(); setMessage("Đã cập nhật."); } catch (e) { setActionError((e as Error).message); } };
  const current = p.listings.filter(l => l.isLatest); const selected = current.find(l => l.transactionType === tab) ?? current[0];
  const cover = p.images.find(x => x.isCover) ?? p.images[0];
  return <><Link className="back-link" href={selected?.transactionType === "SALE" ? "/sale" : "/rent"}><ArrowLeft size={16} />Quay lại kho bất động sản</Link><Title title={p.title || "Hồ sơ chưa có tiêu đề"} description={`${p.code} · ${label(p.propertyType)} · ${[p.addressLine, p.wardCommune, p.provinceCity].filter(Boolean).join(", ")}`}><Badge value={p.visibility} />{p.access.edit && <Button variant="outline" onClick={() => setModal("edit")}><Pencil size={16} />Sửa hồ sơ</Button>}{p.access.admin && <Button variant="outline" onClick={() => setModal("visibility")}>Quản lý hiển thị</Button>}</Title>{message && <p className="success" role="status">{message}</p>}{actionError && <ErrorBox message={actionError} />}
    <div className="detail-columns"><section><div className="gallery panel">{cover ? <button className="cover-image" onClick={() => setLightbox(cover.id)}><img src={`/api/app/images/${cover.id}`} alt={cover.caption || p.title} /></button> : <Empty>Thêm ảnh thực tế để hoàn thiện hồ sơ.</Empty>}<div className="gallery-thumbs">{p.images.map(img => <button key={img.id} onClick={() => setLightbox(img.id)} aria-label={`Phóng to ${img.caption || "ảnh"}`}><img src={`/api/app/images/${img.id}`} alt={img.caption || "Ảnh bất động sản"} /></button>)}</div>{p.access.edit && <Button variant="outline" onClick={() => setModal("gallery")}><Upload size={16} />Quản lý ảnh ({p.images.length}/20)</Button>}</div><section className="panel"><h2>Thông tin bất động sản</h2><div className="facts">{[["Loại hình", label(p.propertyType)], ["Diện tích sử dụng", p.usableArea ? `${p.usableArea} m²` : "—"], ["Diện tích đất", p.landArea ? `${p.landArea} m²` : "—"], ["Phòng ngủ", p.bedrooms], ["Phòng tắm", p.bathrooms], ["Tầng / tổng tầng", `${p.floorNumber ?? "—"} / ${p.totalFloors ?? "—"}`], ["Hướng nhà", p.houseDirection], ["Hướng ban công", p.balconyDirection], ["Mặt tiền (m)", p.frontage], ["Đường vào (m)", p.accessRoadWidth], ["Dự án / tòa nhà", p.projectBuilding], ["Phụ trách", p.responsibleUser?.name]].map(([k, v]) => <div key={String(k)}><span>{String(k)}</span><strong>{v == null || v === "" ? "—" : String(v)}</strong></div>)}</div>{p.mapUrl && <a className="text-link" href={p.mapUrl} target="_blank" rel="noopener noreferrer">Mở vị trí trên bản đồ ↗</a>}{["description", "highlights", "furnishing", "amenities", "viewingNotes"].map((key, i) => p[key] ? <div className="text-section" key={key}><h3>{["Mô tả", "Điểm nổi bật", "Nội thất", "Tiện ích", "Ghi chú dẫn khách"][i]}</h3><p>{String(p[key])}</p></div> : null)}<div className="text-section"><h3>Thông tin pháp lý</h3><Badge value={p.legalStatus} /><p>{p.legalSummary || "Chưa có tóm tắt pháp lý."}</p>{p.verifiedAt ? <small className="muted">Xác minh lúc {date(String(p.verifiedAt))}</small> : null}<p>{p.verificationNotes}</p></div></section></section>
    <aside><section className="panel listing-panel"><div className="section-heading"><h2>Giao dịch</h2>{p.access.admin && <Button size="sm" variant="outline" onClick={() => setModal("newListing")}><Plus size={15} />Đợt mới</Button>}</div><div className="tabs">{current.map(l => <button key={l.id} className={selected?.id === l.id ? "active" : ""} onClick={() => setTab(l.transactionType)}>{label(l.transactionType)}<Badge value={l.status} /></button>)}</div>{selected ? <><p className="eyebrow">ĐỢT {selected.cycleNumber} · {label(selected.priceMode)}</p><div className="detail-price">{money(selected.amount)}{selected.rentPeriod && <small> / {label(selected.rentPeriod)}</small>}</div>{selected.pricePerSquareMeter && <p className="muted">{money(selected.pricePerSquareMeter)}/m² · theo {selected.saleAreaBasis === "landArea" ? "diện tích đất" : "diện tích sử dụng"}</p>}<div className={selected.stale ? "stale-note" : "confirmation-note"}><Clock3 size={17} /><div>{selected.stale ? "Cần kiểm tra lại tình trạng" : "Lần xác nhận gần nhất"}<small>{date(selected.lastConfirmedAt)}</small></div></div><div className="listing-conditions">{listingFormFields(selected.transactionType).filter(f => !["priceMode", "amount", "rentPeriod", "saleAreaBasis"].includes(f.name) && selected[f.name] !== null && selected[f.name] !== "").map(f => <div key={f.name}><span>{f.label}</span><strong>{f.type === "date" ? String(selected[f.name]).slice(0, 10) : String(selected[f.name])}</strong></div>)}</div>{p.access.edit && <div className="stack-actions">{["AVAILABLE", "DEPOSITED"].includes(selected.status) && <><Button variant="outline" onClick={() => act(`listings/${selected.id}/confirm`, { expectedVersion: selected.version })}><Check size={16} />Đã xác nhận tình trạng</Button><Button variant="outline" onClick={() => setModal(`listing:${selected.id}`)}>Sửa giá và điều kiện</Button></>}<Button onClick={() => setModal(`status:${selected.id}`)} disabled={!["AVAILABLE", "DEPOSITED"].includes(selected.status) && !p.access.admin}>{["AVAILABLE", "DEPOSITED"].includes(selected.status) ? "Đổi trạng thái" : "Sửa sai trạng thái (quản trị)"}</Button></div>}</> : <Empty>Chưa có đợt giao dịch. Quản trị viên có thể tạo đợt mới.</Empty>}</section>
    {p.access.sensitive && <section className="panel sensitive-panel"><div className="section-heading"><h2><ShieldCheck size={18} />Thông tin riêng tư</h2>{p.access.editSensitive && <Button size="sm" variant="outline" onClick={() => setModal("owner")}>Sửa</Button>}</div><p className="muted">Chỉ người được cấp quyền mới có thể xem.</p><dl className="owner-info">{[["Chủ nhà", p.owner?.name], ["Điện thoại", p.owner?.phone], ["Zalo", p.owner?.zalo], ["Nguồn", p.owner?.source], ["Ghi chú nhạy cảm", p.owner?.sensitiveNotes]].map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{v || "—"}</dd></div>)}</dl>{selected && <div className="commission-info"><h3>Hoa hồng dự kiến</h3><p>{selected.commissionType === "AMOUNT" ? money(selected.expectedCommissionAmount) : selected.commissionType === "RATE" ? `${selected.expectedCommissionRate}%` : "Chưa có"}</p><p>{selected.commissionNote}</p>{p.access.editSensitive && <Button size="sm" variant="outline" onClick={() => setModal(`commission:${selected.id}`)}>Sửa hoa hồng</Button>}</div>}<h3>Giấy tờ</h3><div className="document-list">{p.documents?.map(d => <div key={d.id}><a href={`/api/app/documents/${d.id}`}>{d.originalName}<small>{d.documentType} · {(d.bytes / 1024).toFixed(0)} KB</small></a>{p.access.editSensitive && <Button variant="ghost" size="sm" aria-label={`Xóa ${d.originalName}`} onClick={() => setModal(`deleteDocument:${d.id}`)}><Trash2 size={16} /></Button>}</div>)}</div>{p.access.editSensitive && <FileUpload p={p} document done={reload} />}</section>}
    {p.access.admin && <section className="panel"><h2>Quyền trên hồ sơ</h2><p className="muted">Người phụ trách và quyền truy cập được quản lý độc lập.</p>{p.permissions?.map(item => <div className="permission-row" key={item.userId}><strong>{item.user.name}</strong><small>{item.canEdit ? "Được sửa" : "Không sửa"} · {item.canViewSensitive ? "Xem riêng tư" : "Không riêng tư"}</small></div>)}<Button variant="outline" onClick={() => setModal("permissions")}>Cấp / thu hồi quyền</Button><Button variant="ghost" onClick={() => setModal("assign")}>Gán người phụ trách</Button></section>}</aside></div>
    {p.access.history && <section className="panel"><h2>Lịch sử giao dịch và chỉnh sửa</h2><div className="history-grid"><div><h3>Các đợt giao dịch</h3>{p.listings.map(l => <details className="history-item" key={l.id}><summary>{label(l.transactionType)} · Đợt {l.cycleNumber} · {label(l.status)} {l.isLatest && "(mới nhất)"}</summary>{l.history?.map(h => <p key={h.id}>{date(h.createdAt)} · {h.actor.name}<br />{h.fromStatus ? `${label(h.fromStatus)} → ` : ""}{label(h.toStatus)}{h.reason && ` · ${h.reason}`}</p>)}{p.access.admin && !["AVAILABLE", "DEPOSITED"].includes(l.status) && <Button variant="outline" size="sm" onClick={() => setModal(`status:${l.id}`)}>Sửa sai có lý do</Button>}</details>)}</div><div><h3>100 thay đổi gần nhất</h3>{p.audits?.map(a => <details className="history-item" key={a.id}><summary>{label(a.action)} · {a.actor.name}<small>{date(a.createdAt)}</small></summary><pre>{JSON.stringify(a.diff, null, 2)}</pre></details>)}</div></div></section>}
    <Dialog open={!!lightbox} onOpenChange={() => setLightbox(undefined)} title="Ảnh bất động sản"><img className="lightbox" src={lightbox ? `/api/app/images/${lightbox}` : undefined} alt={p.title} /></Dialog>
    <Dialog open={!!modal} onOpenChange={v => { if (!v) setModal(""); }} title={modal === "edit" ? "Sửa hồ sơ" : modal === "gallery" ? "Quản lý ảnh" : modal.startsWith("status:") ? "Cập nhật trạng thái giao dịch" : "Quản lý hồ sơ"}>
      {modal === "edit" && <PropertyForm property={p} done={done} />}
      {modal === "gallery" && <GalleryEditor p={p} reload={reload} />}
      {modal === "visibility" && <DataForm fields={[{ name: "visibility", label: "Trạng thái hiển thị", options: options(p.visibility === "ARCHIVED" ? ["PAUSED"] : ["DRAFT", "PUBLISHED", "PAUSED", "ARCHIVED"]) }]} initial={{ visibility: p.visibility === "ARCHIVED" ? "PAUSED" : p.visibility }} submit={v => mutate(`properties/${id}/visibility`, { ...v, expectedVersion: p.version })} onDone={done} submitLabel="Xác nhận thay đổi hiển thị" />}
      {modal === "newListing" && <NewListing p={p} done={done} />}
      {modal.startsWith("listing:") && <ListingForm property={p} listing={p.listings.find(l => l.id === modal.split(":")[1])!} type={p.listings.find(l => l.id === modal.split(":")[1])!.transactionType} done={done} />}
      {modal.startsWith("status:") && <StatusForm listing={p.listings.find(l => l.id === modal.split(":")[1])!} done={done} />}
      {modal === "owner" && <DataForm fields={[{ name: "name", label: "Tên chủ nhà" }, { name: "phone", label: "Số điện thoại" }, { name: "zalo", label: "Zalo" }, { name: "source", label: "Nguồn" }, { name: "sensitiveNotes", label: "Ghi chú nhạy cảm / bằng chứng xác minh", type: "textarea" }]} initial={p.owner ?? {}} schema={ownerSchema} transform={v => ({ ...v, expectedVersion: p.version })} submit={v => mutate(`properties/${id}/owner`, v)} onDone={done} />}
      {modal.startsWith("commission:") && <CommissionForm listing={p.listings.find(l => l.id === modal.split(":")[1])!} done={done} />}
      {["permissions", "assign"].includes(modal) && <PermissionForm p={p} assign={modal === "assign"} done={done} />}
      {modal.startsWith("deleteDocument:") && <><p>Xóa giấy tờ này? Tệp sẽ được đưa vào hàng đợi dọn dẹp.</p><Button variant="destructive" onClick={async () => { try { await mutate(`documents/${modal.split(":")[1]}`, { expectedVersion: p.version }, "DELETE"); done(); } catch (e) { setActionError((e as Error).message); setModal(""); } }}>Xác nhận xóa</Button></>}
    </Dialog>
  </>;
}
function NewListing({ p, done }: { p: PropertyDTO; done: () => void }) { const [type, setType] = useState<"RENT" | "SALE">("RENT"); return <><label className="field">Loại giao dịch<select value={type} onChange={e => setType(e.target.value as "RENT" | "SALE")}><option value="RENT">Cho thuê</option><option value="SALE">Mua bán</option></select></label><p className="muted">Đợt cũ được giữ nguyên. Chỉ tạo được khi không có đợt cùng loại đang mở.</p><ListingForm key={type} property={p} type={type} done={done} /></>; }
function StatusForm({ listing, done }: { listing: ListingDTO; done: () => void }) {
  const [warning, setWarning] = useState(false); const [pending, setPending] = useState<Record<string, unknown>>();
  const correction = !["AVAILABLE", "DEPOSITED"].includes(listing.status);
  return <><p className="muted">{correction ? "Sửa sai trạng thái kết thúc: bắt buộc ghi lý do. Để chào lại tài sản, dùng Tạo đợt mới." : `Hiện tại: ${label(listing.status)}. Thay đổi sẽ được ghi vào lịch sử.`}</p><DataForm fields={[{ name: "status", label: "Trạng thái mới", options: options(["AVAILABLE", "DEPOSITED", listing.transactionType === "RENT" ? "RENTED" : "SOLD", "WITHDRAWN"].filter(v => v !== listing.status)) }, { name: "reason", label: "Lý do", type: "textarea", hint: "Bắt buộc khi hủy cọc, rút tin hoặc sửa sai." }]} submit={async v => { const data = { ...v, correction, expectedVersion: listing.version }; try { await mutate(`listings/${listing.id}/status`, data); done(); } catch (e) { if (e instanceof ApiError && e.code === "OTHER_LISTING_OPEN") { setPending(data); setWarning(true); } throw e; } }} submitLabel="Xác nhận đổi trạng thái" />
  <Dialog open={warning} onOpenChange={setWarning} title="Còn đợt giao dịch khác đang mở" description="Xem xét đợt bán/thuê còn lại trước khi hoàn tất."><DataForm fields={[{ name: "otherListingAction", label: "Xử lý đợt còn lại", options: [{ value: "KEEP", label: "Giữ đợt còn lại" }, { value: "WITHDRAW", label: "Rút đợt còn lại" }] }, { name: "otherListingReason", label: "Lý do", required: true, type: "textarea" }]} submit={v => mutate(`listings/${listing.id}/status`, { ...pending, ...v })} onDone={done} submitLabel="Xác nhận cả hai đợt" /></Dialog></>;
}
function CommissionForm({ listing, done }: { listing: ListingDTO; done: () => void }) {
  const fields = [{ name: "commissionType", label: "Kiểu hoa hồng", options: options(["NONE", "AMOUNT", "RATE"]) }, { name: "expectedCommissionAmount", label: "Số tiền (VND)", type: "number" as const }, { name: "expectedCommissionRate", label: "Tỷ lệ (0–100%)", type: "number" as const }, { name: "commissionNote", label: "Ghi chú hoa hồng", type: "textarea" as const }];
  return <DataForm fields={fields} initial={listing} schema={commissionSchema} transform={v => ({ ...normalizeFields(v, fields), expectedVersion: listing.version })} submit={v => mutate(`listings/${listing.id}/commission`, v)} onDone={done} />;
}
function PermissionForm({ p, assign, done }: { p: PropertyDTO; assign: boolean; done: () => void }) {
  const { data, error, loading, reload } = useResource<UserDTO[]>("users");
  if (loading) return <Loading />; if (error || !data) return <ErrorBox message={error} retry={reload} />;
  return <DataForm fields={assign ? [{ name: "responsibleUserId", label: "Người phụ trách", options: [{ value: "", label: "Chưa giao" }, ...data.map(u => ({ value: u.id, label: `${u.name} · ${u.email}` }))] }] : [{ name: "userId", label: "Tài khoản", options: data.map(u => ({ value: u.id, label: `${u.name} · ${u.email}` })) }, { name: "canEdit", label: "Quyền chỉnh sửa", options: [{ value: "false", label: "Không" }, { value: "true", label: "Có" }] }, { name: "canViewSensitive", label: "Quyền xem thông tin riêng tư", options: [{ value: "false", label: "Không" }, { value: "true", label: "Có" }] }]} initial={assign ? { responsibleUserId: p.responsibleUserId } : { userId: data[0]?.id, canEdit: "false", canViewSensitive: "false" }} submit={v => mutate(`properties/${p.id}/${assign ? "assign" : "permissions"}`, { expectedVersion: p.version, ...(assign ? { responsibleUserId: v.responsibleUserId || null } : { userId: v.userId, canEdit: v.canEdit === "true", canViewSensitive: v.canViewSensitive === "true" }) })} submitLabel={assign ? "Giao phụ trách" : "Lưu quyền (cả hai Không = thu hồi)"} onDone={done} />;
}
function FileUpload({ p, document = false, done }: { p: PropertyDTO; document?: boolean; done: () => void }) {
  const [files, setFiles] = useState<File[]>([]); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState(0); const [error, setError] = useState("");
  return <div className="upload-box"><label><Upload size={20} /><strong>{document ? "Thêm giấy tờ riêng tư" : "Thêm ảnh thực tế"}</strong><small>{document ? "PDF, JPEG, PNG, WebP · tối đa 20 MB/tệp" : "JPEG, PNG, WebP · tối đa 10 MB/ảnh"}</small><input aria-label={document ? "Chọn giấy tờ" : "Chọn ảnh"} type="file" multiple accept={document ? ".pdf,.jpg,.jpeg,.png,.webp" : ".jpg,.jpeg,.png,.webp"} disabled={busy} onChange={e => setFiles(Array.from(e.target.files ?? []))} /></label>{files.length > 0 && <div className="upload-previews">{files.map((file, i) => <UploadPreview key={`${file.name}-${i}`} file={file} />)}</div>}{error && <ErrorBox message={error} />}{busy && <progress max={100} value={progress} aria-label="Tiến độ tải lên" />}{files.length > 0 && <Button disabled={busy} onClick={async () => {
    setBusy(true); setError(""); let version = p.version;
    try { for (let i = 0; i < files.length; i++) { const form = new FormData(); form.append("file", files[i]); form.append("kind", document ? "document" : "image"); form.append("expectedVersion", String(version));
      const response = await new Promise<{ version: number }>((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open("POST", `/api/app/properties/${p.id}/upload`); xhr.upload.onprogress = e => { if (e.lengthComputable) setProgress(Math.round((i + e.loaded / e.total) / files.length * 100)); }; xhr.onload = () => { try { const data = JSON.parse(xhr.responseText); if (xhr.status >= 200 && xhr.status < 300) resolve(data); else reject(new Error(data.message)); } catch { reject(new Error("Phản hồi tải tệp không hợp lệ.")); } }; xhr.onerror = () => reject(new Error("Mất kết nối khi tải tệp. Vui lòng thử lại.")); xhr.send(form); }); version = response.version; }
      setFiles([]); done();
    } catch (e) { setError((e as Error).message); done(); } finally { setBusy(false); }
  }}>{busy ? "Đang tải…" : `Tải lên ${files.length} tệp`}</Button>}</div>;
}
function UploadPreview({ file }: { file: File }) {
  // Preview stays local and is released on unmount.
  const [url] = useState(() => file.type.startsWith("image/") ? URL.createObjectURL(file) : "");
  return <div>{url && <PreviewImage url={url} name={file.name} />}<small>{file.name}</small></div>;
}
function PreviewImage({ url, name }: { url: string; name: string }) { return <img src={url} alt={name} onLoad={() => URL.revokeObjectURL(url)} />; }
function GalleryEditor({ p, reload }: { p: PropertyDTO; reload: () => void }) {
  const [error, setError] = useState(""); const [remove, setRemove] = useState<string>();
  const save = async (ids: string[], coverId: string) => { try { await mutate(`properties/${p.id}/gallery`, { imageIds: ids, coverId, expectedVersion: p.version }); reload(); } catch (e) { setError((e as Error).message); } };
  return <>{error && <ErrorBox message={error} />}<div className="gallery-editor">{p.images.map((img, index) => <div key={img.id}><img src={`/api/app/images/${img.id}`} alt={img.caption || "Ảnh hồ sơ"} /><span>{img.isCover ? "Ảnh bìa" : `Ảnh ${index + 1}`}</span><div className="actions"><Button variant="ghost" size="sm" aria-label={`Đặt ảnh ${index + 1} làm bìa`} onClick={() => save(p.images.map(x => x.id), img.id)}><Star size={16} /></Button><Button variant="ghost" size="sm" disabled={index === 0} aria-label="Đưa ảnh lên" onClick={() => { const ids = p.images.map(x => x.id); [ids[index - 1], ids[index]] = [ids[index], ids[index - 1]]; save(ids, p.images.find(x => x.isCover)!.id); }}><ArrowUp size={16} /></Button><Button variant="ghost" size="sm" disabled={index === p.images.length - 1} aria-label="Đưa ảnh xuống" onClick={() => { const ids = p.images.map(x => x.id); [ids[index + 1], ids[index]] = [ids[index], ids[index + 1]]; save(ids, p.images.find(x => x.isCover)!.id); }}><ArrowDown size={16} /></Button><Button variant="ghost" size="sm" aria-label="Xóa ảnh" onClick={() => setRemove(img.id)}><Trash2 size={16} /></Button></div></div>)}</div><FileUpload p={p} done={reload} /><Dialog open={!!remove} onOpenChange={() => setRemove(undefined)} title="Xóa ảnh này?"><p>Ảnh sẽ bị gỡ khỏi hồ sơ. Ảnh bìa và thứ tự sẽ được cập nhật.</p><Button variant="destructive" onClick={async () => { try { await mutate(`images/${remove}`, { expectedVersion: p.version }, "DELETE"); setRemove(undefined); reload(); } catch (e) { setError((e as Error).message); setRemove(undefined); } }}>Xác nhận xóa</Button></Dialog></>;
}
